# App\Entity\Product:
#   properties:
#     name:
#       - NotBlank: { message: 'Le nom du produit ne peut pas être vide !' }
#       - Length:
#           {
#             min: 3,
#             max: 255,
#             minMessage: 'Le nom du produit doit faire plus de 3 caractères !',
#           }
#     price:
#       - NotBlank: { message: 'Le prix du produit ne peut pas être vide !' }
